default['operation']['folder1'] = 'file1' 
default['operation']['folder2'] = 'file2' 
default['operation']['folder3'] = 'file3' 
default['operation']['folder4'] = 'file4' 
default['operation']['folder5'] = 'file5' 
